### ISSUE TITLE
Integer argument asks for non-integer characters

### ISSUE THREAD

**Issue by King-click** [Uxtron-team/Uxtron-bot-docs#15]
### In what ways is the bot malfunctioning?

Other

### Description

@hi-there-child @DecodedFinn @Creepermonst 
The bot asks for a non-integer character (`w`) for an integer field (the 'winners' argument)

### How can you reproduce this bug?

Type `/giveaway` and fill out all the arguments correctly. When you send the command, the bot will reply with 'please provide the number of winners for the giveaway!'.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/65468855/178493162-0780e0c6-89ad-41ee-8bdb-97f42ee24c2a.png)
![image](https://user-images.githubusercontent.com/65468855/178493294-630d71ec-b516-4791-ab72-81687e7537d8.png)

### Agreements

- [X] The issue listed in this report was experienced while using the bot under normal circumstances.
- [X] I have at least put some effort into making sure this issue has not been previously reported by another user.
- [X] I acknowledge that once I submit this report, I give all admins and moderators permission to publicize this report, with all details included, and with my username publicly visible.
- [X] I am confident that this report is genuine and is an actual error in the bot, and have adequately described the issue so the admins have enough information to reproduce this error and fix it.

**Comment by hi-there-child** [comment]
bro it's 11pm why r u doing this rn

**Comment by hi-there-child** [comment]
i'll try to fix this sometime later

**Comment by hi-there-child** [comment]
This issue has been fixed!
